# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calc_pb2 as calc__pb2


class CalculadoraStub(object):
	"""Definição do serviço
	"""

	def __init__(self, channel):
		"""Constructor.

		Args:
		  channel: A grpc.Channel.
		"""
		self.Somar = channel.unary_unary(
			'/calc.Calculadora/Somar',
			request_serializer=calc__pb2.DoisArgs.SerializeToString,
			response_deserializer=calc__pb2.Resposta.FromString,
		)
		self.Subtrair = channel.unary_unary(
			'/calc.Calculadora/Subtrair',
			request_serializer=calc__pb2.DoisArgs.SerializeToString,
			response_deserializer=calc__pb2.Resposta.FromString,
		)
		self.Dividir = channel.unary_unary(
			'/calc.Calculadora/Dividir',
			request_serializer=calc__pb2.DoisArgs.SerializeToString,
			response_deserializer=calc__pb2.Resposta.FromString,
		)
		self.Multiplicar = channel.unary_unary(
			'/calc.Calculadora/Multiplicar',
			request_serializer=calc__pb2.DoisArgs.SerializeToString,
			response_deserializer=calc__pb2.Resposta.FromString,
		)
		self.Potencia = channel.unary_unary(
			'/calc.Calculadora/Potencia',
			request_serializer=calc__pb2.DoisArgs.SerializeToString,
			response_deserializer=calc__pb2.Resposta.FromString,
		)
		self.Fatorial = channel.unary_unary(
			'/calc.Calculadora/Fatorial',
			request_serializer=calc__pb2.UmArgIntSemSinal.SerializeToString,
			response_deserializer=calc__pb2.RespostaIntSemSinal.FromString,
		)
		self.RaizQuad = channel.unary_unary(
			'/calc.Calculadora/RaizQuad',
			request_serializer=calc__pb2.UmArg.SerializeToString,
			response_deserializer=calc__pb2.Resposta.FromString,
		)


class CalculadoraServicer(object):
	"""Definição do serviço
	"""

	def Somar(self, request, context):
		"""Operações básicas
		"""
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details('Method not implemented!')
		raise NotImplementedError('Method not implemented!')

	def Subtrair(self, request, context):
		# missing associated documentation comment in .proto file
		pass
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details('Method not implemented!')
		raise NotImplementedError('Method not implemented!')

	def Dividir(self, request, context):
		# missing associated documentation comment in .proto file
		pass
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details('Method not implemented!')
		raise NotImplementedError('Method not implemented!')

	def Multiplicar(self, request, context):
		# missing associated documentation comment in .proto file
		pass
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details('Method not implemented!')
		raise NotImplementedError('Method not implemented!')

	def Potencia(self, request, context):
		# missing associated documentation comment in .proto file
		pass
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details('Method not implemented!')
		raise NotImplementedError('Method not implemented!')

	def Fatorial(self, request, context):
		# missing associated documentation comment in .proto file
		pass
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details('Method not implemented!')
		raise NotImplementedError('Method not implemented!')

	def RaizQuad(self, request, context):
		# missing associated documentation comment in .proto file
		pass
		context.set_code(grpc.StatusCode.UNIMPLEMENTED)
		context.set_details('Method not implemented!')
		raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
	rpc_method_handlers = {
		'Somar': grpc.unary_unary_rpc_method_handler(
			servicer.Somar,
			request_deserializer=calc__pb2.DoisArgs.FromString,
			response_serializer=calc__pb2.Resposta.SerializeToString,
		),
		'Subtrair': grpc.unary_unary_rpc_method_handler(
			servicer.Subtrair,
			request_deserializer=calc__pb2.DoisArgs.FromString,
			response_serializer=calc__pb2.Resposta.SerializeToString,
		),
		'Dividir': grpc.unary_unary_rpc_method_handler(
			servicer.Dividir,
			request_deserializer=calc__pb2.DoisArgs.FromString,
			response_serializer=calc__pb2.Resposta.SerializeToString,
		),
		'Multiplicar': grpc.unary_unary_rpc_method_handler(
			servicer.Multiplicar,
			request_deserializer=calc__pb2.DoisArgs.FromString,
			response_serializer=calc__pb2.Resposta.SerializeToString,
		),
		'Potencia': grpc.unary_unary_rpc_method_handler(
			servicer.Potencia,
			request_deserializer=calc__pb2.DoisArgs.FromString,
			response_serializer=calc__pb2.Resposta.SerializeToString,
		),
		'Fatorial': grpc.unary_unary_rpc_method_handler(
			servicer.Fatorial,
			request_deserializer=calc__pb2.UmArgIntSemSinal.FromString,
			response_serializer=calc__pb2.RespostaIntSemSinal.SerializeToString,
		),
		'RaizQuad': grpc.unary_unary_rpc_method_handler(
			servicer.RaizQuad,
			request_deserializer=calc__pb2.UmArg.FromString,
			response_serializer=calc__pb2.Resposta.SerializeToString,
		),
	}
	generic_handler = grpc.method_handlers_generic_handler(
		'calc.Calculadora', rpc_method_handlers)
	server.add_generic_rpc_handlers((generic_handler,))
