# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
	name='calc.proto',
	package='calc',
	syntax='proto3',
	serialized_options=None,
	serialized_pb=_b(
		'\n\ncalc.proto\x12\x04\x63\x61lc\"\x14\n\x05UmArg\x12\x0b\n\x03num\x18\x01 \x01(\x01\"\x1f\n\x10UmArgIntSemSinal\x12\x0b\n\x03num\x18\x01 \x01(\x04\"&\n\x08\x44oisArgs\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04num2\x18\x02 \x01(\x01\"\x1d\n\x08Resposta\x12\x11\n\tresultado\x18\x01 \x01(\x01\"(\n\x13RespostaIntSemSinal\x12\x11\n\tresultado\x18\x01 \x01(\x04\x32\xde\x02\n\x0b\x43\x61lculadora\x12)\n\x05Somar\x12\x0e.calc.DoisArgs\x1a\x0e.calc.Resposta\"\x00\x12,\n\x08Subtrair\x12\x0e.calc.DoisArgs\x1a\x0e.calc.Resposta\"\x00\x12+\n\x07\x44ividir\x12\x0e.calc.DoisArgs\x1a\x0e.calc.Resposta\"\x00\x12/\n\x0bMultiplicar\x12\x0e.calc.DoisArgs\x1a\x0e.calc.Resposta\"\x00\x12,\n\x08Potencia\x12\x0e.calc.DoisArgs\x1a\x0e.calc.Resposta\"\x00\x12?\n\x08\x46\x61torial\x12\x16.calc.UmArgIntSemSinal\x1a\x19.calc.RespostaIntSemSinal\"\x00\x12)\n\x08RaizQuad\x12\x0b.calc.UmArg\x1a\x0e.calc.Resposta\"\x00\x62\x06proto3')
)

_UMARG = _descriptor.Descriptor(
	name='UmArg',
	full_name='calc.UmArg',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='num', full_name='calc.UmArg.num', index=0,
			number=1, type=1, cpp_type=5, label=1,
			has_default_value=False, default_value=float(0),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			serialized_options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	serialized_options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=20,
	serialized_end=40,
)

_UMARGINTSEMSINAL = _descriptor.Descriptor(
	name='UmArgIntSemSinal',
	full_name='calc.UmArgIntSemSinal',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='num', full_name='calc.UmArgIntSemSinal.num', index=0,
			number=1, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			serialized_options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	serialized_options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=42,
	serialized_end=73,
)

_DOISARGS = _descriptor.Descriptor(
	name='DoisArgs',
	full_name='calc.DoisArgs',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='num1', full_name='calc.DoisArgs.num1', index=0,
			number=1, type=1, cpp_type=5, label=1,
			has_default_value=False, default_value=float(0),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			serialized_options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='num2', full_name='calc.DoisArgs.num2', index=1,
			number=2, type=1, cpp_type=5, label=1,
			has_default_value=False, default_value=float(0),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			serialized_options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	serialized_options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=75,
	serialized_end=113,
)

_RESPOSTA = _descriptor.Descriptor(
	name='Resposta',
	full_name='calc.Resposta',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='resultado', full_name='calc.Resposta.resultado', index=0,
			number=1, type=1, cpp_type=5, label=1,
			has_default_value=False, default_value=float(0),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			serialized_options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	serialized_options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=115,
	serialized_end=144,
)

_RESPOSTAINTSEMSINAL = _descriptor.Descriptor(
	name='RespostaIntSemSinal',
	full_name='calc.RespostaIntSemSinal',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='resultado', full_name='calc.RespostaIntSemSinal.resultado', index=0,
			number=1, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			serialized_options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	serialized_options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=146,
	serialized_end=186,
)

DESCRIPTOR.message_types_by_name['UmArg'] = _UMARG
DESCRIPTOR.message_types_by_name['UmArgIntSemSinal'] = _UMARGINTSEMSINAL
DESCRIPTOR.message_types_by_name['DoisArgs'] = _DOISARGS
DESCRIPTOR.message_types_by_name['Resposta'] = _RESPOSTA
DESCRIPTOR.message_types_by_name['RespostaIntSemSinal'] = _RESPOSTAINTSEMSINAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UmArg = _reflection.GeneratedProtocolMessageType('UmArg', (_message.Message,), {
	'DESCRIPTOR': _UMARG,
	'__module__': 'calc_pb2'
	# @@protoc_insertion_point(class_scope:calc.UmArg)
})
_sym_db.RegisterMessage(UmArg)

UmArgIntSemSinal = _reflection.GeneratedProtocolMessageType('UmArgIntSemSinal', (_message.Message,), {
	'DESCRIPTOR': _UMARGINTSEMSINAL,
	'__module__': 'calc_pb2'
	# @@protoc_insertion_point(class_scope:calc.UmArgIntSemSinal)
})
_sym_db.RegisterMessage(UmArgIntSemSinal)

DoisArgs = _reflection.GeneratedProtocolMessageType('DoisArgs', (_message.Message,), {
	'DESCRIPTOR': _DOISARGS,
	'__module__': 'calc_pb2'
	# @@protoc_insertion_point(class_scope:calc.DoisArgs)
})
_sym_db.RegisterMessage(DoisArgs)

Resposta = _reflection.GeneratedProtocolMessageType('Resposta', (_message.Message,), {
	'DESCRIPTOR': _RESPOSTA,
	'__module__': 'calc_pb2'
	# @@protoc_insertion_point(class_scope:calc.Resposta)
})
_sym_db.RegisterMessage(Resposta)

RespostaIntSemSinal = _reflection.GeneratedProtocolMessageType('RespostaIntSemSinal', (_message.Message,), {
	'DESCRIPTOR': _RESPOSTAINTSEMSINAL,
	'__module__': 'calc_pb2'
	# @@protoc_insertion_point(class_scope:calc.RespostaIntSemSinal)
})
_sym_db.RegisterMessage(RespostaIntSemSinal)

_CALCULADORA = _descriptor.ServiceDescriptor(
	name='Calculadora',
	full_name='calc.Calculadora',
	file=DESCRIPTOR,
	index=0,
	serialized_options=None,
	serialized_start=189,
	serialized_end=539,
	methods=[
		_descriptor.MethodDescriptor(
			name='Somar',
			full_name='calc.Calculadora.Somar',
			index=0,
			containing_service=None,
			input_type=_DOISARGS,
			output_type=_RESPOSTA,
			serialized_options=None,
		),
		_descriptor.MethodDescriptor(
			name='Subtrair',
			full_name='calc.Calculadora.Subtrair',
			index=1,
			containing_service=None,
			input_type=_DOISARGS,
			output_type=_RESPOSTA,
			serialized_options=None,
		),
		_descriptor.MethodDescriptor(
			name='Dividir',
			full_name='calc.Calculadora.Dividir',
			index=2,
			containing_service=None,
			input_type=_DOISARGS,
			output_type=_RESPOSTA,
			serialized_options=None,
		),
		_descriptor.MethodDescriptor(
			name='Multiplicar',
			full_name='calc.Calculadora.Multiplicar',
			index=3,
			containing_service=None,
			input_type=_DOISARGS,
			output_type=_RESPOSTA,
			serialized_options=None,
		),
		_descriptor.MethodDescriptor(
			name='Potencia',
			full_name='calc.Calculadora.Potencia',
			index=4,
			containing_service=None,
			input_type=_DOISARGS,
			output_type=_RESPOSTA,
			serialized_options=None,
		),
		_descriptor.MethodDescriptor(
			name='Fatorial',
			full_name='calc.Calculadora.Fatorial',
			index=5,
			containing_service=None,
			input_type=_UMARGINTSEMSINAL,
			output_type=_RESPOSTAINTSEMSINAL,
			serialized_options=None,
		),
		_descriptor.MethodDescriptor(
			name='RaizQuad',
			full_name='calc.Calculadora.RaizQuad',
			index=6,
			containing_service=None,
			input_type=_UMARG,
			output_type=_RESPOSTA,
			serialized_options=None,
		),
	])
_sym_db.RegisterServiceDescriptor(_CALCULADORA)

DESCRIPTOR.services_by_name['Calculadora'] = _CALCULADORA

# @@protoc_insertion_point(module_scope)
